name: Node CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [14.x, 16.x]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - run: npm i -g pnpm
      - run: pnpm -v
      - run: pnpm --ignore-engines
      - run: pnpm doc:build
        env:
          CI: true
          PROGRESS: none
          NODE_OPTIONS: --max_old_space_size=4096
