

name: github pages

on:
  push:
    branches:
      - main # default branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Install pnpm
        run: curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@next-7
      - name: Install dependencies
        run: pnpm install
        run: pnpm crowdin:sync
      - uses: webfactory/ssh-agent@v0.5.4
      - name: Release to GitHub Pages
        run: |
          pnpm run doc:deploy